micronaut:
  application:
    name: dataOperation
datasources:
  default:
    url: jdbc:sqlserver://localhost:1433;databaseName=mydb
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: Anemoi
    password: Anemoi@123
    schema-generate: CREATE_DROP
    dialect: SQL_SERVER
jpa.default.properties.hibernate.hbm2ddl.auto: update
